main: me.rexlmanu.signplugin.SignPlugin
author: rexlManu
name: SignPlugin
version: 1.0
description: A sign plugin thats have many big citybuild servers
commands:
  sign:
    usage: Use to sign a item
    permission: sign.unsign
  unsign:
    permission: sign.unsign
    usage: Use to unsign a item